# Dependencies
markdown: kramdown
# markdown:         redcarpet
# highlighter:      pygments

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            mwsatman
tagline:          'personal website'
description:      'Postdoctoral Research Fellow, <br/>
  <a href="https://research.tuni.fi/iines/" target="_blank">Intelligent Network Systems</a>
  <br/>
  Automation Technology and Mechanical Engineering
  <br/>
  Faculty of Engineering and Natural Sciences
  <br/>
  Tampere University'
url:              https://mwsatman.github.io
baseurl:          /

author:
  name:           'Made Widhi Surya Atman'
  url:            https://mwsatman.github.io

gems: [jekyll-paginate]
paginate: 5
paginate_path: "page:num"
paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/mwsatman
